[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
subscription_model = "6PyMsXWBKo77maWZir1kpE8i71Kuwprgm5hR9e5Ng2r3"

[programs.devnet]
subscription_model = "6PyMsXWBKo77maWZir1kpE8i71Kuwprgm5hR9e5Ng2r3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"
